static const char *tr_shop(void) {
    if (language == 1) {
        return "Магазин";
    }
    return "Shop";
}

static const char *tr_candies(void) {
    if (language == 1) {
        return "Леденцы";
    }
    return "Candies";
}

static const char *tr_class_ordinary(void) {
    if (language == 1) {
        return "Обычный";
    }
    return "Ordinary";
}

static const char *tr_class_azum(void) {
    if (language == 1) {
        return "Азум";
    }
    return "Azum";
}

static const char *tr_class_ordinary_desc(void) {
    return "I was the first";
}

static const char *tr_class_azum_desc(void) {
    return "Lived once, buried twice...";
}

static const char *tr_class_santa(void) {
    if (language == 1) {
        return "Дед Мороз";
    }
    return "Santa";
}

static const char *tr_class_santa_desc(void) {
    return "It's 12:00 AM!";
}

static const char *tr_class_astra(void) {
    if (language == 1) {
        return "Астра";
    }
    return "Astra";
}

static const char *tr_class_astra_desc(void) {
    return "I love you, Azum...";
}

static const char *tr_class_ebuc(void) {
    return "ebuC";
}

static const char *tr_class_ebuc_desc(void) {
    return "Tr4pp3d";
}
